import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { execSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'))

function gitSha(): string {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim()
  } catch {
    return 'unknown'
  }
}

/**
 * The app's one and only service worker — offline shell AND FCM push in a
 * single file, generated because a worker can't read `import.meta.env` and
 * Firebase's config has to be baked in at build time.
 *
 * Two things here are load-bearing and easy to undo by accident:
 *
 *  1. It keeps the filename `/sw.js`. Registering a DIFFERENT script URL at
 *     the same scope REPLACES the existing registration, so splitting push
 *     into its own `/firebase-messaging-sw.js` would race the cache worker and
 *     whichever lost would silently swallow every notification. Same URL with
 *     new bytes just updates in place, so existing installs migrate on their
 *     own with no unregister dance.
 *  2. There must be no `public/sw.js`. Vite copies `public/` into `dist` AFTER
 *     the bundle is emitted, so a same-named file there would quietly
 *     overwrite this and ship a worker with no push handler — no error, no
 *     warning, just silence.
 */
function serviceWorker(env: Record<string, string>) {
  const config = {
    apiKey: env.VITE_FIREBASE_API_KEY,
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: env.VITE_FIREBASE_APP_ID,
  }
  // Must track the `firebase` version in package.json — the compat bundles
  // loaded here are a separate copy of the SDK from the app's.
  const SDK = '12.14.0'
  const source = `/* Generated by vite.config.ts — do not edit, and do not add a public/sw.js. */
importScripts('https://www.gstatic.com/firebasejs/${SDK}/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/${SDK}/firebase-messaging-compat.js')
firebase.initializeApp(${JSON.stringify(config)})

const CACHE_NAME = 'fairshare-v2'

// Cache the app shell on install
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(['/']))
  )
  self.skipWaiting()
})

// Clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  )
  self.clients.claim()
})

// Network-first strategy: try network, fall back to cache
self.addEventListener('fetch', (event) => {
  // Skip non-GET and cross-origin requests
  if (event.request.method !== 'GET') return
  if (!event.request.url.startsWith(self.location.origin)) return

  // Skip Firebase/API requests (let Firestore handle its own caching)
  if (event.request.url.includes('firestore.googleapis.com')) return
  if (event.request.url.includes('identitytoolkit.googleapis.com')) return
  if (event.request.url.includes('securetoken.googleapis.com')) return

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        // Cache successful responses
        if (response.ok) {
          const clone = response.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone))
        }
        return response
      })
      .catch(() => {
        // Network failed — serve from cache
        return caches.match(event.request).then((cached) => {
          // For navigation requests, return the cached index.html (SPA)
          if (event.request.mode === 'navigate') {
            return caches.match('/') || cached
          }
          return cached
        })
      })
  )
})

// Last: background messages carrying a notification payload display
// automatically, and taps follow webpush.fcmOptions.link from the function.
firebase.messaging()
`
  return {
    name: 'emit-service-worker',
    generateBundle(this: {
      emitFile: (f: { type: 'asset'; fileName: string; source: string }) => void
    }) {
      this.emitFile({ type: 'asset', fileName: 'sw.js', source })
    },
    // generateBundle doesn't run in `vite dev`, and there's no public/sw.js to
    // fall back on any more, so serve the same bytes from the dev server.
    configureServer(server: {
      middlewares: {
        use: (
          path: string,
          handler: (
            req: unknown,
            res: { setHeader(k: string, v: string): void; end(s: string): void }
          ) => void
        ) => void
      }
    }) {
      server.middlewares.use('/sw.js', (_req, res) => {
        res.setHeader('Content-Type', 'text/javascript')
        res.end(source)
      })
    },
  }
}

// Served at /version.json so `make versions` can ask each site what it runs
function emitVersionJson(buildEnv: string) {
  return {
    name: 'emit-version-json',
    apply: 'build' as const,
    generateBundle(this: { emitFile: (f: { type: 'asset'; fileName: string; source: string }) => void }) {
      this.emitFile({
        type: 'asset',
        fileName: 'version.json',
        source: JSON.stringify({
          version: pkg.version,
          sha: gitSha(),
          builtAt: new Date().toISOString(),
          env: buildEnv,
        }),
      })
    },
  }
}

export default defineConfig(({ mode }) => {
  // The config file can't see import.meta.env, and the service worker needs
  // the active mode's Firebase config baked in — loadEnv reads it here (shell
  // env still wins if set, matching Vite's own precedence).
  const env = loadEnv(mode, process.cwd(), '')
  const buildEnv = env.VITE_BUILD_ENV === 'dev' ? 'dev' : 'prod'
  return {
    plugins: [react(), tailwindcss(), emitVersionJson(buildEnv), serviceWorker(env)],
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version),
      __GIT_SHA__: JSON.stringify(gitSha()),
      __BUILD_DATE__: JSON.stringify(new Date().toISOString().slice(0, 10)),
    },
  }
})
