import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App'
import { AuthProvider } from './hooks/useAuth'
import { ThemeProvider } from './hooks/useTheme'
import { AccentProvider } from './hooks/useAccent'
import { TextScaleProvider } from './hooks/useTextScale'
import { ProfileCacheProvider } from './hooks/useProfileCache'

// The app's ONLY service worker — offline shell and FCM push in one file,
// generated by vite.config.ts. Keep this URL: registering a second script at
// the same scope replaces this registration, and whichever worker lost the
// race would silently drop every notification.
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {})
  })
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ThemeProvider>
      <AccentProvider>
        <TextScaleProvider>
          <AuthProvider>
            <ProfileCacheProvider>
              <App />
            </ProfileCacheProvider>
          </AuthProvider>
        </TextScaleProvider>
      </AccentProvider>
    </ThemeProvider>
  </StrictMode>
)
